# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='work_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
