# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0004_auto_20160417_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=10)),
                ('instagram_cursor', models.TextField(blank=True, null=True)),
                ('empty', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='data_gathered',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='status',
            field=models.CharField(default='idle', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='status_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='ig_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='instagramsource',
            name='instagram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequbot_data.InstagramUser'),
        ),
        migrations.AddField(
            model_name='instagramsource',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequbot_data.SocialAccount'),
        ),
        migrations.AddField(
            model_name='instagramtestsubject',
            name='instagram_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequbot_data.InstagramSource'),
        ),
    ]
