# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0005_auto_20160421_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramsource',
            name='instagram_user',
        ),
        migrations.RemoveField(
            model_name='instagramsource',
            name='social_account',
        ),
        migrations.RenameField(
            model_name='instagramscrapaction',
            old_name='action_type',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='instagramtestsubject',
            name='instagram_source',
        ),
        migrations.AddField(
            model_name='instagramscrapaction',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagramscrapaction',
            name='instagram_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sequbot_data.InstagramUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramscrapaction',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramscrapaction',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagramscrapaction',
            name='source_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='instagramscrapaction',
            name='username_ref',
        ),
        migrations.AlterUniqueTogether(
            name='instagramscrapaction',
            unique_together=set([('social_account', 'instagram_user', 'source')]),
        ),
        migrations.DeleteModel(
            name='InstagramSource',
        ),
    ]
