# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0006_auto_20160425_0005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstagramScrapAction',
            new_name='InstagramSource',
        ),
        migrations.AlterModelTable(
            name='instagramsource',
            table='instagram_source',
        ),
    ]
