# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0007_auto_20160425_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramtestsubject',
            name='instagram_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequbot_data.InstagramSource'),
        ),
    ]
