# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0008_instagramtestsubject_instagram_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramsource',
            old_name='source',
            new_name='source_action',
        ),
        migrations.RemoveField(
            model_name='instagramsource',
            name='source_count',
        ),
        migrations.AlterUniqueTogether(
            name='instagramsource',
            unique_together=set([('social_account', 'instagram_user', 'source_action')]),
        ),
    ]
