# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0009_auto_20160425_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='instagram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequbot_data.InstagramUser'),
        ),
    ]
