# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0010_socialaccount_instagram_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramapierror',
            name='social_account',
        ),
        migrations.RenameField(
            model_name='socialaccount',
            old_name='followings_count',
            new_name='follows_count',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='status_updated',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='init_followers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='init_follows_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='stats_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='InstagramApiError',
        ),
    ]
