# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0012_auto_20160510_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='auth_retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='status',
            field=models.CharField(max_length=40),
        ),
    ]
