# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0013_auto_20160514_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialaccount',
            old_name='work_days',
            new_name='work_seconds',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='automaton_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
