# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0014_auto_20160514_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='status_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
