# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0015_auto_20160525_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialaccount',
            old_name='target_conditions',
            new_name='ai_config',
        ),
    ]
