# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0016_auto_20160602_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramsource',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='follow_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='followed_by_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='media_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='followers_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='follows_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='init_followers_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='init_follows_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='media_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='work_seconds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
