# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0018_socialaccount_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='password',
            field=models.TextField(),
        ),
    ]
