# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-25 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequbot_data', '0020_instagramtestsubject_is_follow_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
